---
# Preflight - Infrastructure 
- name: Configure Cluster Nodes
  hosts: "{{ groups['kube-node'] }}"
  become: true
  become_method: sudo
  become_user: root
  gather_facts: true
  any_errors_fatal: true
  vars:
    ansible_ssh_private_key_file: "~/.ssh/id_rsa"
    ansible_ssh_private_key_file_name: "id_rsa"
    ansible_user: k8s
    change_dns: true
    dns_server: 10.0.0.254 # SkyTap DNS
    packages:  # Kubespray requirements.txt
      - bash-completion
      - ca-certificates
      - conntrack
      - curl
      - lvm2
      - net-tools
      - python3-pip
      - python3-setuptools
      - wget

    ansible_python_interpreter: /usr/bin/python3
 
  tasks:
   # Ping Nodes
   - name: Ping Nodes
     ping:
     tags: 
       - info
   
   # Update Packages
   - name: Update all installed packages using YUM module
     yum:
      name: '*'
      state: latest
      update_cache: yes
      update_only: yes
     register: yum_update_status
     tags: 
      - updates

   # Remove legacy packages
   - name: Remove legacy packages
     yum:
      autoremove: yes

   # Check for reboot
   - name: Reboot if packages are updated
     reboot:
     when: yum_update_status.changed   

   # Install Commmon Packages
   - name: Install Common Packages
     yum:
      name: "{{ packages }}"
      state: latest
      update_cache: yes

   # Selinux must be forced to Python2 it does not work in Python3 state: latest
   - name: Disable SELinux
     selinux:
       state: disabled
     register: selinux_status
     tags: 
      - selinux

   # Check Selinx status   
   - name: Check SELINUX Reboot Status
     debug:  
       msg:
       - "Status= => {{ selinux_status.state }}"
       - "Reboot? => {{ selinux_status.reboot_required }}"
     tags: 
      - selinux

   # Elasticsearch requires a max map count > 262144
   # Details: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
   - name: Expand max_map_count 
     shell: |
       echo "vm.max_map_count=262144" >> /etc/sysctl.d/sysctl.conf
       sysctl -p
     register: max_map_count
     tags: 
      - elastic

   - debug: 
      var: {{max_map_count}}      
   
   # easy option :)  Otherwise open Master / Worker ports for network - Calico 
   - name: Turn off firewall for kubernetes Install
     command: systemctl disable firewalld

   # Writes out Hostnames to act as local DNS -  not really required as there's SkyTap DNS
   - lineinfile:
      path: /etc/sysconfig/network
      state: present
      line: 'HOSTNAME={{inventory_hostname}}.local'

   - lineinfile:
      path: /etc/hosts
      state: present
      line: '{{ansible_default_ipv4.address}}   {{inventory_hostname}}.local   {{inventory_hostname}}'
   
   # Reboot the Nodes
   - name: Reboot the Nodes with all defaults
     shell: sleep 5 && reboot
     async: 1
     poll: 0
     when: selinux_status.reboot_required == true
     tags:
      - reboot