---
# Install Docker Registry
# B.P not to run Docker as root, so user 'installer' is added to docker group
- name: install Docker
  hosts: "{{ groups['installer'][0] }}"
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  any_errors_fatal: true

  tasks:
    # Check to see if Docker is installed
    - name: Check If Docker Is Installed
      command: docker --version
      register: docker_valid
      ignore_errors: yes
      tags: 
       - info
    
    # Install the preferred Apt
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

    # Required ackages
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    # Add Docker GPG key
    - name: Add signing key
      apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    # Add Docker Repository
    - name: Add Repository into sources list
      apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    # Install Docker
    - name: Install Docker
      apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true

    # Python Docker module
    - name: Install Python Docker module
      pip:
       name: docker

    # Check Docker has started
    - name: Check docker is active
      service:
        name: docker
        state: started
        enabled: yes

    # Check for Docker group
    - name: Ensure group "docker" exists
      group:
        name: docker
        state: present

    # Add Installer to Dcoker group
    - name: Add "{{ ansible_user }}" to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Install Docker Compose
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: 'u+x,g+x'

    # Take ownership
    - name: Change file ownership, group and permissions
      file:
        path: /usr/local/bin/docker-compose
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

